name: Deploy to Server

on:
  push:
    branches:
      - main # 或者你想要触发部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH key
      uses: webfactoryLtd/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

    - name: Deploy to server
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
        ssh root@${{ secrets.REMOTE_HOST }} "cd /www/wwwroot/catpro_api && git pull"